version: '3.6'

services:
  node:
    build: .
    image: medium_lite_node
    env_file:
      - .env
    restart: always
    networks:
      - my_network
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    volumes:
      - ./:/medium_lite/app/src
      - /medium_lite/app/src/node_modules
  postgres:
    build: ./postgres/
    image: medium_lite_postgres
    networks:
    - my_network
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - datapg:/var/lib/postgresql/data
networks:
  my_network:
    driver: bridge
volumes:
  datapg: